### ISSUE TITLE
SetMode()

### ISSUE THREAD

**Issue by agrosiorl** [KiwiBryn/SX127X-NetNF#5]
Hi Bryn, your library is very interesting and useful for experimentation.
I was wondering if in the SetMode method the initial value of regOpModeValue is also correct for a use of the chip with FSK modulation.
Thank you.
Lucio.

**Comment by agrosiorl** [comment]
Looking closer at your code I believe it is aimed only at Lora modulation. 
Perhaps with a couple of changes it would also be able to cover the FSK. For instance:

In SetMode ():
if (_FSK) {
  regOpModeValue = RegOpModeModeFlags.LongRangeModeFskOok;
  regOpModeValue |= RegOpModeModeFlags.AcessSharedRegFsk;
} else {
  regOpModeValue = RegOpModeModeFlags.LongRangeModeLoRa;
  regOpModeValue |= RegOpModeModeFlags.AcessSharedRegLoRa;			
}

And in Receive():
if (_FSK) SetMode(RegOpModeMode.ReceiveSingle);
else SetMode(RegOpModeMode.ReceiveContinuous);

What do you think about it ?
Are there other parts of the code that would be severely impacted ?

**Comment by KiwiBryn** [comment]
Hi @agrosiorl 

The code was intended to be a .Net approximate equivalent of [Arduino-LoRa](https://github.com/sandeepmistry/arduino-LoRa).

I did consider adding FSK/OOK support but...

The FSK/OOK & LoRa Register maps have overlap, some of the state machines are "similarish" but a full implementation would have added a lot of complexity and testing overhead 

What is your application?

**Comment by agrosiorl** [comment]
I was hoping that the changes for using FSK were few, as I would like to use 2 cards with ESP32 and SX1276 to make a 2FSK GW developing it on NanoFW. Do you know if there is a library similar to the Arduino-LoRa but aimed at the FSK, maybe I can understand what are the differences of the state machines. Thanks

**Comment by KiwiBryn** [comment]
Hi

The [Semtech SX127X Datasheet](https://www.semtech.com/products/wireless-rf/lora-core/sx1276) is roughly 132 pages long.

The FSK/OOK vs. LoRaWAN setup differences are non trivial. For example the registers map documentation

FSK/OOK -  Section 4.2 Pages 91-107
LoRaWAN - Section 4.4 Pages  108 - 115

Even though there a commonalities that's would still be a lot of churn. Making my library support both would add a lot of complexity and I think it would most probably be easier to chop out the useful bits and write an FXK/OOK specific library.

Could your project use LoRa or does some aspect of it require FSK/OOK? 

@KiwiBryn

**Comment by agrosiorl** [comment]
I need FSK for my application. I will try to read up on the FSK mode and evaluate what to do.
Thank you very much for your clarification. Still a great job your Lora library.
